name: test
on:
  workflow_dispatch:
      
jobs:
  build:
    name: 启动"${{ matrix.target }}-${{ github.event.inputs.REPO_BRANCH }}"触发编译
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    
    env:
      FOLDER_NAME: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [Lede]
        
        # 请勿对 target: [Lede] 做任何修改
        
    steps:
    
    - name: SSH远程连接（make menuconfig）
      uses: rdp-studio/ssh2actions@main
